# Step 1: Installation and Setup

In [ ]:
import tensorflow as tf
print(tf.__version__)

2.4.0

In [ ]:
import numpy as np
import pandas as pd
import matplotlib.pyplot as plt

In [11]:
#importing dataset
from google.colab import files
uploaded = files.upload()

TypeError: ignored

In [ ]:
print(uploaded)

In [12]:
#checking working directory
!ls

Churn_Modelling.csv  sample_data

# Step 2: Data Preprocessing

In [13]:
#reading the data
df=pd.read_csv('Churn_Modelling.csv')
df.head()

   RowNumber  CustomerId   Surname  ...  IsActiveMember EstimatedSalary Exited
0          1    15634602  Hargrave  ...               1       101348.88      1
1          2    15647311      Hill  ...               1       112542.58      0
2          3    15619304      Onio  ...               0       113931.57      1
3          4    15701354      Boni  ...               0        93826.63      0
4          5    15737888  Mitchell  ...               1        79084.10      0

[5 rows x 14 columns]

In [14]:
df.shape

(10000, 14)

In [15]:
#selecting independent and dependent variables
df

      RowNumber  CustomerId    Surname  ...  IsActiveMember EstimatedSalary Exited
0             1    15634602   Hargrave  ...               1       101348.88      1
1             2    15647311       Hill  ...               1       112542.58      0
2             3    15619304       Onio  ...               0       113931.57      1
3             4    15701354       Boni  ...               0        93826.63      0
4             5    15737888   Mitchell  ...               1        79084.10      0
...         ...         ...        ...  ...             ...             ...    ...
9995       9996    15606229   Obijiaku  ...               0        96270.64      0
9996       9997    15569892  Johnstone  ...               1       101699.77      0
9997       9998    15584532        Liu  ...               1        42085.58      1
9998       9999    15682355  Sabbatini  ...               0        92888.52      1
9999      10000    15628319     Walker  ...               0        38190.78      0

[10000 rows x 14 columns]

In [19]:

df.drop(['RowNumber'	,'CustomerId',	'Surname','Exited'], axis=1)

      CreditScore Geography  Gender  ...  HasCrCard  IsActiveMember  EstimatedSalary
0             619    France  Female  ...          1               1        101348.88
1             608     Spain  Female  ...          0               1        112542.58
2             502    France  Female  ...          1               0        113931.57
3             699    France  Female  ...          0               0         93826.63
4             850     Spain  Female  ...          1               1         79084.10
...           ...       ...     ...  ...        ...             ...              ...
9995          771    France    Male  ...          1               0         96270.64
9996          516    France    Male  ...          1               1        101699.77
9997          709    France  Female  ...          0               1         42085.58
9998          772   Germany    Male  ...          1               0         92888.52
9999          792    France  Female  ...          1               0         38190.78

[10000 rows x 10 columns]

In [20]:
x=df.drop(['RowNumber'	,'CustomerId',	'Surname','Exited'], axis=1)

In [21]:
x.shape

(10000, 10)

In [22]:
y=df['Exited']

In [24]:
y.head()

0    1
1    0
2    1
3    0
4    0
Name: Exited, dtype: int64

In [25]:
#independent var
x.head()

   CreditScore Geography  Gender  ...  HasCrCard  IsActiveMember  EstimatedSalary
0          619    France  Female  ...          1               1        101348.88
1          608     Spain  Female  ...          0               1        112542.58
2          502    France  Female  ...          1               0        113931.57
3          699    France  Female  ...          0               0         93826.63
4          850     Spain  Female  ...          1               1         79084.10

[5 rows x 10 columns]

In [26]:
#dependent var
y.head()

0    1
1    0
2    1
3    0
4    0
Name: Exited, dtype: int64

In [27]:
#encoding categorical data - like gender and geography
from sklearn.preprocessing import LabelEncoder

In [28]:
label_1= LabelEncoder()
x['Geography']=label_1.fit_transform(x['Geography'])

In [29]:
x.head()

   CreditScore  Geography  Gender  ...  HasCrCard  IsActiveMember  EstimatedSalary
0          619          0  Female  ...          1               1        101348.88
1          608          2  Female  ...          0               1        112542.58
2          502          0  Female  ...          1               0        113931.57
3          699          0  Female  ...          0               0         93826.63
4          850          2  Female  ...          1               1         79084.10

[5 rows x 10 columns]

In [30]:
label_2=LabelEncoder()
x['Gender'] = label_2.fit_transform(x['Gender'])

In [32]:
x.head(15)

    CreditScore  Geography  Gender  ...  HasCrCard  IsActiveMember  EstimatedSalary
0           619          0       0  ...          1               1        101348.88
1           608          2       0  ...          0               1        112542.58
2           502          0       0  ...          1               0        113931.57
3           699          0       0  ...          0               0         93826.63
4           850          2       0  ...          1               1         79084.10
5           645          2       1  ...          1               0        149756.71
6           822          0       1  ...          1               1         10062.80
7           376          1       0  ...          1               0        119346.88
8           501          0       1  ...          0               1         74940.50
9           684          0       1  ...          1               1         71725.73
10          528          0       1  ...          0               0         80181.12
11          497          2       1  ...          1               0         76390.01
12          476          0       0  ...          1               0         26260.98
13          549          0       0  ...          0               0        190857.79
14          635          2       0  ...          1               1         65951.65

[15 rows x 10 columns]

In [33]:
#Avoiding Dummy variable trap
x=pd.get_dummies(x, drop_first=True, columns=['Geography'])

In [34]:
x.head(10)

   CreditScore  Gender  Age  ...  EstimatedSalary  Geography_1  Geography_2
0          619       0   42  ...        101348.88            0            0
1          608       0   41  ...        112542.58            0            1
2          502       0   42  ...        113931.57            0            0
3          699       0   39  ...         93826.63            0            0
4          850       0   43  ...         79084.10            0            1
5          645       1   44  ...        149756.71            0            1
6          822       1   50  ...         10062.80            0            0
7          376       0   29  ...        119346.88            1            0
8          501       1   44  ...         74940.50            0            0
9          684       1   27  ...         71725.73            0            0

[10 rows x 11 columns]

In [85]:
#splitting data into train and test set
from sklearn.model_selection import train_test_split

In [90]:
x_train,x_test,y_train,y_test = train_test_split(x,y, test_size=0.2,random_state=0)

In [91]:
x_train

      CreditScore  Gender  Age  ...  EstimatedSalary  Geography_1  Geography_2
7389          667       0   34  ...        163830.64            0            1
9275          427       1   42  ...         57098.00            1            0
2995          535       0   29  ...        185630.76            0            0
5316          654       1   40  ...        173617.09            0            1
356           850       0   57  ...        132298.49            0            1
...           ...     ...  ...  ...              ...          ...          ...
9225          594       0   32  ...        162961.79            1            0
4859          794       0   22  ...        107753.07            0            1
3264          738       1   35  ...        181429.87            0            0
9845          590       0   38  ...        148750.16            0            1
2732          623       0   48  ...        118855.26            1            0

[8000 rows x 11 columns]

In [92]:
#Feature Scaling
from sklearn.preprocessing import StandardScaler
sc = StandardScaler()
x_train = sc.fit_transform(x_train)
x_test =sc.transform(x_test) #no need of fit, already done in the train obj in prev step

In [93]:
x_train

array([[ 0.16958176, -1.09168714, -0.46460796, ...,  1.10643166,
        -0.5698444 ,  1.74309049],
       [-2.30455945,  0.91601335,  0.30102557, ..., -0.74866447,
         1.75486502, -0.57369368],
       [-1.19119591, -1.09168714, -0.94312892, ...,  1.48533467,
        -0.5698444 , -0.57369368],
       ...,
       [ 0.9015152 ,  0.91601335, -0.36890377, ...,  1.41231994,
        -0.5698444 , -0.57369368],
       [-0.62420521, -1.09168714, -0.08179119, ...,  0.84432121,
        -0.5698444 ,  1.74309049],
       [-0.28401079, -1.09168714,  0.87525072, ...,  0.32472465,
         1.75486502, -0.57369368]])

In [94]:
#all values are now not having a scale difference
#now same thing

# Step 3: Building the Model

In [95]:
#Initializing the ANN
#creating the object

model=tf.keras.models.Sequential()

In [96]:
#adding first hidden input layer
#units=6 (11+1/2=6)
#activation func = relu
#input dimension=11
model.add(tf.keras.layers.Dense(units=6,activation='relu',input_dim=11))

In [97]:
#adding second hidden layer, no need to specify input_dim here.
model.add(tf.keras.layers.Dense(units=6,activation='relu'))

In [98]:
#Output layer, units=1 cuz only 1 output,activation func=sigmoid because binary output
model.add(tf.keras.layers.Dense(units=1,activation='sigmoid'))

In [99]:
#compiling model  
model.compile(optimizer='adam',loss='binary_crossentropy', metrics=['accuracy'])

In [100]:
model.summary()

Model: "sequential_1"
_________________________________________________________________
Layer (type)                 Output Shape              Param #
=================================================================
dense_3 (Dense)              (None, 6)                 72
_________________________________________________________________
dense_4 (Dense)              (None, 6)                 42
_________________________________________________________________
dense_5 (Dense)              (None, 1)                 7
=================================================================
Total params: 121
Trainable params: 121
Non-trainable params: 0
_________________________________________________________________

# Step 4: Training the model

In [101]:
#y_train is 1 column - it is a vector. whereas x_train is a numpy array so i have to convert y_train into numpy array
model.fit(x_train,y_train.to_numpy(),batch_size=32,epochs=10)

Epoch 1/10
250/250 [==============================] - 1s 964us/step - loss: 0.6021 - accuracy: 0.7287
Epoch 2/10
250/250 [==============================] - 0s 949us/step - loss: 0.4891 - accuracy: 0.7970
Epoch 3/10
250/250 [==============================] - 0s 997us/step - loss: 0.4480 - accuracy: 0.8128
Epoch 4/10
250/250 [==============================] - 0s 996us/step - loss: 0.4427 - accuracy: 0.8073
Epoch 5/10
250/250 [==============================] - 0s 1ms/step - loss: 0.4279 - accuracy: 0.8150
Epoch 6/10
250/250 [==============================] - 0s 988us/step - loss: 0.4251 - accuracy: 0.8119
Epoch 7/10
250/250 [==============================] - 0s 1ms/step - loss: 0.4182 - accuracy: 0.8213
Epoch 8/10
250/250 [==============================] - 0s 970us/step - loss: 0.4119 - accuracy: 0.8268
Epoch 9/10
250/250 [==============================] - 0s 990us/step - loss: 0.4088 - accuracy: 0.8303
Epoch 10/10
250/250 [==============================] - 0s 1ms/step - loss: 0.4050 - accuracy: 0.8331

# Step 5: Model evaluation and prediction

In [102]:
test_loss, test_acc = model.evaluate(x_test,y_test)

63/63 [==============================] - 0s 776us/step - loss: 0.4014 - accuracy: 0.8425

In [103]:
 print('Test accuracy: {}'.format(test_acc))

Test accuracy: 0.8424999713897705

In [104]:
y_pred= model.predict_classes(x_test)

/usr/local/lib/python3.6/dist-packages/tensorflow/python/keras/engine/sequential.py:450: UserWarning: `model.predict_classes()` is deprecated and will be removed after 2021-01-01. Please use instead:* `np.argmax(model.predict(x), axis=-1)`,   if your model does multi-class classification   (e.g. if it uses a `softmax` last-layer activation).* `(model.predict(x) > 0.5).astype("int32")`,   if your model does binary classification   (e.g. if it uses a `sigmoid` last-layer activation).
  warnings.warn('`model.predict_classes()` is deprecated and '

In [105]:
print(y_pred)

[[0]
 [0]
 [0]
 ...
 [0]
 [0]
 [0]]

In [106]:
print(y_test)

9394    0
898     1
2398    0
5906    0
2343    0
       ..
1037    0
2899    0
9549    0
2740    0
6690    0
Name: Exited, Length: 2000, dtype: int64

In [108]:
y_test=y_test.to_numpy()

In [109]:
print('the predicted value for index 20 is {}'.format(y_pred[19]))
print('the real value for index 20 is {}'.format(y_test[19]))

the predicted value for index 20 is [0]
the real value for index 20 is 0

In [110]:
#confusion matrix
from sklearn.metrics import confusion_matrix, accuracy_score
cm=confusion_matrix(y_test,y_pred)
print(cm)

[[1535   60]
 [ 255  150]]

In [111]:
acc_cm= accuracy_score(y_test,y_pred)
print(acc_cm)

0.8425